using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FileEditor
{
    /// <summary>
    /// Data service abstract class for manipulating data
    /// DO NOT EDIT THIS FILE
    /// </summary>
    public abstract class DataServiceBase
    {
        protected List<int> numbers;

        public DataServiceBase()
        {
            numbers = new List<int>();
        }

        /// <summary>
        /// Create a new test file in the current directory
        /// </summary>
        public abstract void CreateTestFile();

        /// <summary>
        /// Read each line of the text file
        /// </summary>
        /// <returns>
        /// Enumerable object containing all test data
        /// </returns>
        public abstract void ReadTestData();

        /// <summary>
        /// Read each line of the text file
        /// </summary>
        /// <param name="data"></param>
        public abstract void AppendTestData(int number);

        /// <summary>
        /// Read each line of the text file
        /// </summary>
        /// <param name="numbers"></param>
        public void DisplayTestData()
        {
            Console.WriteLine("Test data read from file");
            Console.WriteLine("----------------------------------------");

            foreach (int number in numbers)
            {
                Console.WriteLine(number);
            }
            Console.WriteLine();
        }

        /// <summary>
        /// Display the total of all data lines
        /// </summary>
        /// <param name="numbers"></param>
        public void DisplayTotal()
        {
            Console.WriteLine($"The total of all numbers is {numbers.Sum()}");
        }

        /// <summary>
        /// CHALLENGE
        /// Converts the file to VALID and WELL-FORMED XML
        /// </summary>
        public virtual void ConvertToXML()
        {
            throw new NotImplementedException();
        }
    }
}
